services:
  web:
    image: golang:1.22
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    command: go run cmd/vodeno-task-web/main.go
    environment:
      - ENV=dev
      - WEB_API_PORT=8080
      - DATABASE_URL=postgres://vodeno-task:pa$$word@db:5432/vodeno-task
      - SMTP_URL=mailcatcher:1025

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: vodeno-task
      POSTGRES_PASSWORD: pa$$word
      POSTGRES_DB: vodeno-task
    volumes:
      - "./schema/:/docker-entrypoint-initdb.d/"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vodeno-task" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "8086:1080"
    expose:
      - "1025"