// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID            int64
	Email         string
	Title         pgtype.Text
	Content       pgtype.Text
	MailingID     pgtype.Int8
	InsertionTime pgtype.Timestamp
}

type Mailing struct {
	ID       int64
	IsLocked bool
}
